# Site
name: "Algorithms and Data Structures"
title: "Algorithms and Data Structures"
description: "Курс по алгоритмам и структурам данных в школе ЦПМ"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /algo-cource-cte
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

collections:
  pages:
    output: true
    permalink: /:path

# Authors
authors:
  i_love_myself:
    name: i_love_myself
    display_name: Денис Сапожников
    email: sapozhnikov01@mail.ru
    tg: https://t.me/i_1ove_myse1f
    description: "ВШЭ Прикладная математика и информатика 23', ШАД Data Science 22'"
  danlark1:
    name: danlark1
    display_name: Данила Кутенин
    tg: https://t.me/experimentalchill
    description: "Work in big tech companies and currently working at Google doing pipeline data processing systems. Check out Dataflow and Apache Beam."
  smax:
    name: smax
    display_name: smax
    description: "cp-blog"
  algorithmica:
    name: algorithmica
    display_name: algorithmica
    description: "algorithmica.org"


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
